# Generated by Django 4.2.2 on 2023-12-14 14:46

import base.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("R", "Reply"), ("P", "Post")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("user", models.CharField(max_length=25)),
                ("content", models.TextField(max_length=500)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.upload_to
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=25)),
                (
                    "post",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="base.post"
                    ),
                ),
            ],
        ),
    ]
