# Generated by Django 4.2.2 on 2023-06-27 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('content', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 6, 27, 6, 30, 34, 662299, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
