# Generated by Django 4.2.2 on 2023-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_post_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(blank=True, to='base.post'),
        ),
    ]
