# Generated by Django 4.2.2 on 2023-07-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='posts', to='base.post'),
        ),
    ]
