# Generated by Django 4.2.2 on 2023-07-08 17:02

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_to),
        ),
    ]
